# Generated by Django 4.2 on 2025-06-19 20:28

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_accueil_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accueil',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('services', 8), ('projects', 11), ('expertise', 15), ('testimonials', 18), ('contact', 20)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('background_image', 2), ('button_text', 1), ('button_url', 3)]], {}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('icon', 1), ('title', 1), ('description', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('title', 1), ('service_items', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('image', 2), ('title', 1), ('category', 1)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 1), ('project_items', 10)]], {}), 12: ('wagtail.blocks.IntegerBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('number', 12), ('title', 1), ('description', 5)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('title', 1), ('expertise_items', 14)]], {}), 16: ('wagtail.blocks.StructBlock', [[('quote', 5), ('author', 1), ('company', 1)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('title', 1), ('testimonials', 17)]], {}), 19: ('wagtail.blocks.EmailBlock', (), {}), 20: ('wagtail.blocks.StructBlock', [[('title', 1), ('address', 1), ('phone', 1), ('email', 19)]], {})}),
        ),
    ]
