# Generated by Django 5.0.14 on 2025-06-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_accueil_homepage_body_homepage_hero_cta_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accueil',
            new_name='AccueilPage',
        ),
    ]
