# Generated by Django 5.0.14 on 2025-06-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_accueil_accueilpage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccueilPage',
            new_name='HomeePage',
        ),
        migrations.RenameModel(
            old_name='HomePage',
            new_name='SimplePage',
        ),
    ]
