# Generated by Django 5.0.14 on 2025-06-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_accueilpage_homeepage_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeePage',
            new_name='HomePage',
        ),
    ]
