# Generated by Django 5.0.14 on 2025-07-04 17:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_homeepage_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('advanced_hero', 16), ('services', 20), ('projects', 23), ('expertise', 27), ('testimonials', 30), ('contact', 32)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('background_image', 2), ('button_text', 1), ('button_url', 3)]], {}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Utiliser une vidéo comme fond ?', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image de fond', 'required': False}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Lien vidéo (YouTube, Vimeo...)', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('start', 'Aligné à gauche'), ('center', 'Centré'), ('end', 'Aligné à droite')]}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 12: ('wagtail.blocks.URLBlock', (), {'required': True}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Bouton principal (plein)'), ('secondary', 'Bouton secondaire (outline)')]}), 14: ('wagtail.blocks.StructBlock', [[('text', 11), ('url', 12), ('style', 13)]], {'required': False}), 15: ('wagtail.blocks.ListBlock', (14,), {'required': False}), 16: ('wagtail.blocks.StructBlock', [[('use_video', 5), ('background_image', 6), ('background_video', 7), ('title', 8), ('subtitle', 9), ('text_position', 10), ('buttons', 15)]], {}), 17: ('wagtail.blocks.TextBlock', (), {}), 18: ('wagtail.blocks.StructBlock', [[('icon', 1), ('title', 1), ('description', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.StructBlock', [[('title', 1), ('service_items', 19)]], {}), 21: ('wagtail.blocks.StructBlock', [[('image', 2), ('title', 1), ('category', 1)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {}), 23: ('wagtail.blocks.StructBlock', [[('title', 1), ('project_items', 22)]], {}), 24: ('wagtail.blocks.IntegerBlock', (), {}), 25: ('wagtail.blocks.StructBlock', [[('number', 24), ('title', 1), ('description', 17)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {}), 27: ('wagtail.blocks.StructBlock', [[('title', 1), ('expertise_items', 26)]], {}), 28: ('wagtail.blocks.StructBlock', [[('quote', 17), ('author', 1), ('company', 1)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {}), 30: ('wagtail.blocks.StructBlock', [[('title', 1), ('testimonials', 29)]], {}), 31: ('wagtail.blocks.EmailBlock', (), {}), 32: ('wagtail.blocks.StructBlock', [[('title', 1), ('address', 1), ('phone', 1), ('email', 31)]], {})}),
        ),
    ]
