# Generated by Django 5.0.14 on 2025-07-06 16:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('advanced_hero', 15), ('services', 19), ('projects', 22), ('expertise', 26), ('testimonials', 29), ('contact', 31)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('background_image', 2), ('button_text', 1), ('button_url', 3)]], {}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Utiliser une vidéo comme fond ?', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image de fond', 'required': False}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Lien vidéo (YouTube, Vimeo...)', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('start', 'Aligné à gauche'), ('center', 'Centré'), ('end', 'Aligné à droite')]}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Bouton principal (plein)'), ('secondary', 'Bouton secondaire (outline)')]}), 13: ('wagtail.blocks.StructBlock', [[('text', 11), ('url', 3), ('style', 12)]], {'required': False}), 14: ('wagtail.blocks.ListBlock', (13,), {'required': False}), 15: ('wagtail.blocks.StructBlock', [[('use_video', 5), ('background_image', 6), ('background_video', 7), ('title', 8), ('subtitle', 9), ('text_position', 10), ('buttons', 14)]], {}), 16: ('wagtail.blocks.TextBlock', (), {}), 17: ('wagtail.blocks.StructBlock', [[('icon', 1), ('title', 1), ('description', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('title', 1), ('service_items', 18)]], {}), 20: ('wagtail.blocks.StructBlock', [[('image', 2), ('title', 1), ('category', 1)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('title', 1), ('project_items', 21)]], {}), 23: ('wagtail.blocks.IntegerBlock', (), {}), 24: ('wagtail.blocks.StructBlock', [[('number', 23), ('title', 1), ('description', 16)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {}), 26: ('wagtail.blocks.StructBlock', [[('title', 1), ('expertise_items', 25)]], {}), 27: ('wagtail.blocks.StructBlock', [[('quote', 16), ('author', 1), ('company', 1)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('title', 1), ('testimonials', 28)]], {}), 30: ('wagtail.blocks.EmailBlock', (), {}), 31: ('wagtail.blocks.StructBlock', [[('title', 1), ('address', 1), ('phone', 1), ('email', 30)]], {})}),
        ),
    ]
